version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:15.1
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432